### ISSUE TITLE
user flow when choosing an answer

### ISSUE THREAD

**Issue by harrygfox** [Jbarget/guess-who#1]
I intended in the designs for the user to receive feedback about their choice at the time of their choice - so if they chose incorrectly it would tell them they chose the wrong answer and tell them which one is correct. If they chose correctly it would tell them they chose the correct answer. This is why the user chooses AND THEN chooses next. 
If this is not gonna be part of the build then the next button is just inconvenient and it should be removed.

**Comment by Jbarget** [comment]
Hey hey, so this is built in already, I applied classes to the buttons depending on whether the user clicks the correct name or not, I’m responding on my phone at the mo but can give more detail tomorrow

**Comment by harrygfox** [comment]
@Jbarget 
![image](https://user-images.githubusercontent.com/7805691/53350450-00164000-3917-11e9-9055-865e3ec64685.png)
this is the HTML when I select an answer - I won't be able to style based on the order classes appear in the attribute - I need a unique class name

**Comment by Jbarget** [comment]
oh that should only have one `incorrectAnswer`, i'll fix that 🛠

**Comment by harrygfox** [comment]
Do you mean `correctAnswer`?

**Comment by Jbarget** [comment]
Ah Im forgetting to reset them at the beginning of each round it seems

**Comment by harrygfox** [comment]
I think this is done!
