### ISSUE TITLE
Different styles for different Quiz size?

### ISSUE THREAD

**Issue by harrygfox** [Jbarget/guess-who#4]
This actually wasn't part of the initial requirements - I introduced it as part of my designs, kind of without thinking about the implications, but just assuming that these would be treated as 3 distinct quizzes. That need not be the case. I'm just wondering, @Jbarget, about client / end-user expectations. Is it worth building 3 different quiz colour palettes?

**Comment by Jbarget** [comment]
Nah it’s absolutely fine with just one

**Comment by harrygfox** [comment]
Cool 🐝 'ns
