### ISSUE TITLE
Altered Markup to enhance styles

### ISSUE THREAD

**Issue by harrygfox** [Jbarget/guess-who#6]
Hi @Jbarget 

this block here:
```js
fastdom.mutate(() => {
      incorrect.forEach(incorrectAnswer => {
        const node = document.createElement('LI')
        const imgNode = document.createElement('IMG')
        var textNode = document.createTextNode(incorrectAnswer.realName)
        imgNode.src = incorrectAnswer.image
        imgNode.class = 'incorrectAnswerImg'
        textNode.class = 'incorrectAnswerName'

        node.appendChild(imgNode)
        node.appendChild(textNode)
        incorrectAnswersList.appendChild(node)
      })
      document.getElementById('score').textContent = rounds.length - incorrect.length
    })
```

renders a list as follows: 
```html
<ul class="end-wrong-answers" id="incorrect-answers">
  <li>
    <img src="./images/one.jpg">
    Jamie six
  </li>
  <li>
    <img src="./images/one.jpg">
    Jamie six
  </li>
</ul>
```

The problem i'm having with styling is I can't **only** select the image labels since the text value is inside the `<li>` and not its own `<span>`. As a result I'm struggling to render the designs where the image is on the left and the text is on the right.

Would it be possible to, instead of creating a text node, create a `span` elements and insert the text value into that element?

**Comment by harrygfox** [comment]
not really a bug, but you know what i mean

**Comment by Jbarget** [comment]
this is done 👍 added a commit on your branch 

cd270158911fea6b0265b614a39dc2ed438111fc
